user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

manager_admin:
    resource: "@ManagerAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
_imagine:
    resource: .
    type:     imagine