Manager\AdminBundle\Entity\Image:
  type: entity
  table: dbla_cms_image
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    filename:
      type: string
    mime_type:
      type: string
      nullable: true
    original_filename:
      type: string
    hash:
      type: string  
  lifecycleCallbacks:
        prePersist: [ prepareFile ]
        preUpdate: [ prepareOldFile, prepareFile ]
        postPersist: [ uploadFile ]
        postUpdate: [ uploadFile, removeOldFile ]
        postRemove: [ removeFile ]
        
  repositoryClass: Manager\AdminBundle\Repository\ImageRepository